<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8abdb008-0b32-42d4-9e70-c7e1d0d2d291</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XFit.Services\XFit.Services.csproj" />
  </ItemGroup>

</Project>
