//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFit.Utilities.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XFit.Utilities.Exceptions.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط اکانت کاربران فعال قابل ویرایش .
        /// </summary>
        public static string ActiveAccountCanBeEdited {
            get {
                return ResourceManager.GetString("ActiveAccountCanBeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط اکانت کاربران فعال قابل مسدود شدن میباشد .
        /// </summary>
        public static string ActiveUserCanBeBanned {
            get {
                return ResourceManager.GetString("ActiveUserCanBeBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط گذرواژه اکانت کاربران فعال را میتوان تغییر داد .
        /// </summary>
        public static string ActiveUserPasswordCanBeChanged {
            get {
                return ResourceManager.GetString("ActiveUserPasswordCanBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر فعال را نمی توان پاک کرد .
        /// </summary>
        public static string CannotDeleteActiveUser {
            get {
                return ResourceManager.GetString("CannotDeleteActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید منقضی شده است .
        /// </summary>
        public static string CodeExpired {
            get {
                return ResourceManager.GetString("CodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید اشتباه میباشد .
        /// </summary>
        public static string CodeIsWrong {
            get {
                return ResourceManager.GetString("CodeIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این شماره همراه قبلا ثبت نام کرده است .
        /// </summary>
        public static string DuplicateRegister {
            get {
                return ResourceManager.GetString("DuplicateRegister", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to جلسه مورد نظر یافت نشد.
        /// </summary>
        public static string GymAttendanceNotFound {
            get {
                return ResourceManager.GetString("GymAttendanceNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت ورود برای این رزرو وجود ندارد.
        /// </summary>
        public static string GymAttendanceCheckInUnavailable {
            get {
                return ResourceManager.GetString("GymAttendanceCheckInUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ثبت عدم حضور فقط برای رزروهای پایان‌یافته امکان‌پذیر است.
        /// </summary>
        public static string GymAttendanceNoShowUnavailable {
            get {
                return ResourceManager.GetString("GymAttendanceNoShowUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سطح باشگاه یافت نشد.
        /// </summary>
        public static string GymLevelNotFound {
            get {
                return ResourceManager.GetString("GymLevelNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to باشگاه یافت نشد.
        /// </summary>
        public static string GymNotFound {
            get {
                return ResourceManager.GetString("GymNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مقدار واریز معتبر نیست.
        /// </summary>
        public static string InvalidDepositAmount {
            get {
                return ResourceManager.GetString("InvalidDepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Balance!.
        /// </summary>
        public static string InsufficientBalancedException {
            get {
                return ResourceManager.GetString("InsufficientBalancedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonce not found!.
        /// </summary>
        public static string NonceNotFoundException {
            get {
                return ResourceManager.GetString("NonceNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه قدیمی اشتباه است .
        /// </summary>
        public static string OldPasswordIsWrong {
            get {
                return ResourceManager.GetString("OldPasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه یکبار مصرف هر 5 دقیقه یکبار میتوان ارسال شود .
        /// </summary>
        public static string PaswordSend {
            get {
                return ResourceManager.GetString("PaswordSend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تایید پرداخت ناموفق بود.
        /// </summary>
        public static string PaymentVerificationFailed {
            get {
                return ResourceManager.GetString("PaymentVerificationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سرویس پرداخت در دسترس نیست.
        /// </summary>
        public static string PaymentServiceUnavailable {
            get {
                return ResourceManager.GetString("PaymentServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه قبلا تایید شده است .
        /// </summary>
        public static string PhoneNumberIsActive {
            get {
                return ResourceManager.GetString("PhoneNumberIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کاربر تایید نشده است .
        /// </summary>
        public static string PhoneNumberNotActive {
            get {
                return ResourceManager.GetString("PhoneNumberNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش یافت نشد .
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اس ام اس هر 2 دقیقه یک بار میتواند ارسال شود .
        /// </summary>
        public static string SMSTime {
            get {
                return ResourceManager.GetString("SMSTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Authorization Error .
        /// </summary>
        public static string UserAuthorize {
            get {
                return ResourceManager.GetString("UserAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر نمی تواند اکانت خود را بن کند.
        /// </summary>
        public static string UserCantBanHimself {
            get {
                return ResourceManager.GetString("UserCantBanHimself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر نمی تواند اکانت خود را پاک کند.
        /// </summary>
        public static string UserCantDeleteHimself {
            get {
                return ResourceManager.GetString("UserCantDeleteHimself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User don&apos;t have permission for this action .
        /// </summary>
        public static string UserForbbiden {
            get {
                return ResourceManager.GetString("UserForbbiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت کاربر مسدود میباشد .
        /// </summary>
        public static string UserIsBan {
            get {
                return ResourceManager.GetString("UserIsBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد .
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
